### PR TITLE
We have Contact! Expansion Content Inclusion

### PR DESCRIPTION
**Pull request by Parasite42**
Added Contact content to the framework's weapon list, and people list. also added some marksmen DLC and APEX DLC content that were missing from the framework's accessory list.

### CODE REVIEW

**Comment by Coryf88** [comment]
I'm not too familiar with the way Arma handles premium weapon/attachment content.
If someone doesn't have the Contact DLC, would they receive the premium content _advertisement_ once, but still be able to fully use the items?
Would the _advertisement_ be displayed once for the weapon and additional times for each DLC attachment?
Would the _advertisement_ be displayed again after some interval?

**Comment by Parasite42** [comment]
it would probably require testing but as far as i know, the advertisement shows up whenever the player has a DLC item equipped. additionally if a mission uses DLC items that a player has touched, it will display an advertisement at the end of the mission or whenever they exit.
For weapons and gear it shows the standard advertisement pop up on the right hand side along with a button prompt (LShift+P) if a player has a weapon or item equipped, as far as i know the player still has 'full functionality' except for picking it up either when dropped or found. Eventually after using a DLC item for a while, the game will obscure the player's vision by overlaying banners onscreen until the DLC item is removed from the player or dropped, which makes using DLC items very annoying.
For vehicles you're either locked out of them entirely, as any attempt to get inside of a DLC vehicle will create a popup. i'm not sure if forcing a player inside a vehicle will create the same effect as the DLC weapons.
honestly i'm not too sure either and some of this is probably changed, i'd ask to get help from someone who doesn't own contact or premium DLC

**Comment by HeroesMaker** [comment]
it work the same has any other official DLCs, if someone doesn't have it he can't use it, but he can see it.
so this is just restricted to players themselves, it doesn't restrict enemy/friendly AI.

**Comment by Coryf88** [comment]
Applied in 81c4382e02ae616be4a7e65036fc0b0456744837, de58b4f46c37dcb0d4d8829062b95768e5008175, and ff213234c28c7efba7b231a2a01c6ea1a850928b commits

**Pull request closed without merging**
